run hrpsys_tools_config.py within unittest.TestCase
because we have too much https://github.com/fkanehiro/hrpsys-base/issues/905#issue-121912200 like error on meldoic/source

```
user@ubuntu-18:~/rtmros_ws/src/rtmros_common/hrpsys_tools/test$ python ./test-pa10.py  --host 127.0.01 --port 2809 PA10Controller\(Robot
\)0   -i
[ROSUNIT] Outputting test results to /home/user/.ros/test_results/hrpsys_tools/rosunit-test_interactive.xml
omniORB: (0) 2019-08-05 10:25:28.723303: From endpoint: giop:tcp:198.199.111.144:2810. Detected GIOP 1.2 protocol error in input message
. giopImpl12.cc:171. Connection is closed.
[Testcase: test] ... ERROR!
ERROR: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_UnMarshalResults, CORBA.COMPLETED_YES)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "./test-pa10.py", line 12, in test
    execfile(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../scripts", "hrpsys_tools_config.py"), globals(), local_dict)
  File "/home/user/rtmros_ws/src/rtmros_common/hrpsys_tools/test/../scripts/hrpsys_tools_config.py", line 38, in &lt;module&gt;
    hcf.waitForRTCManagerAndRoboHardware(robotname=sys.argv[1])
  File "/home/user/rtmros_ws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 996, in waitForRTCManagerAndRoboHardware
    return self.waitForRTCManagerAndRobotHardware(robotname=robotname, managerhost=managerhost)
  File "/home/user/rtmros_ws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 1006, in waitForRTCManagerAndRobotHardware
    self.waitForRobotHardware(robotname)
  File "/home/user/rtmros_ws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 972, in waitForRobotHardware
    print(self.configurator_name + "findComps -&gt; %s : %s isActive? = %s " % (self.rh.name(), self.rh,  self.rh.isActive()))
  File "/home/user/rtmros_ws/devel/lib/python2.7/dist-packages/hrpsys/rtm.py", line 205, in name
    cprof = self.ref.get_component_profile()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/OpenRTM_aist/RTM_IDL/RTC_idl.py", line 1321, in get_component_profile
    return self._obj.invoke("get_component_profile", _0_RTC.RTObject._d_get_component_profile, args)
```